displayName=Flipping Masterminds
author=ca-gray
description=Track GE market movers, set price alerts, monitor buy limit cooldowns and get Discord integrated GE slots!
tags=grand_exchange,prices,flipping,merching,alerts,buy_limits,market
plugins=com.flippingmasterminds.FlippingMastermindsPlugin
build=standard
